---
- name: Initialize the ansibleop account on a system
  hosts: "{{ INVENTORY }}"
  # remote_user: root|ansible|ansibleop|whatever you need here
  # become: true|false
  vars_files:
    - secrets.yml

  vars:
    default_op_account:
      username: "ansibleop"
      password: "{{ secret_default_op_password }}"
      uid: 1000
      gid: 1000
    op_account_ssh_pub_key: "NOTDEFINED"
    op_account_homedir: ""
    gen_ssh_key: false
    config_primary_op: true  # Are we initializing the operator account on the Tower system?


  vars_prompt:
    - name: op_username
      prompt: "Operator account username?"
      default: "{{ default_op_account.username }}"
      private: no
    
    - name: op_password
      prompt: "Operator account password?"
      default: "{{ default_op_account.password }}"
      private: yes
    
    - name: op_uid
      prompt: "Operator uid?"
      default: "{{ default_op_account.uid }}"
      private: no

    - name: op_gid
      prompt: "Operator gid?"
      default: "{{ default_op_account.gid }}"

  tasks:
    - name: create the Ansible operator account
      user:
        name: "{{ op_username }}"
        create_home: true
        uid: "{{ op_uid }}"
        state: present

    - name: Create the Ansbile operator account ssh key and cache the public key into a fact for primary account only
      block:
        - name: Create the RSA keys for the primary operator account
          user:
            name: "{{ op_username }}"
            generate_ssh_key: true
            ssh_key_bits: 2048
            ssh_key_file: .ssh/id_rsa
            state: present

        - name: Lookup newly create Operator account home directory
          getent:
            database: passwd
            key: "{{ op_username }}"

        - name: Load the Ansible Operator public key into a fact
          set_fact:
            op_account_homedir: "{{ getent_passwd[op_username].4 }}"

        - name: Update authorized_keys file to include the new public key
          lineinfile:
            path: "{{ op_account_homedir }}/.ssh/authorized_keys"
            owner: "{{ op_username }}"
            group: "{{ op_username }}"
            mode: 0400
            line: "{{ lookup('file', op_account_homedir + '/.ssh/id_rsa.pub') }}"
            create: true
            backup: true
            state: present
      when: config_primary_op    

    - name: Craete sudoers entry for the Ansible Operator
      template:
        src: files/sudoer-ansibleop.j2
        dest: /etc/sudoers.d/{{ op_username }}
        owner: root
        group: root
        umask: 0440

    - name: Update authorized_keys file to include the primary operator account public key
      lineinfile:
        path: "{{ op_account_homedir }}/.ssh/authorized_keys"
        owner: "{{ op_username }}"
        group: "{{ op_username }}"
        mode: 0400
        line: "{{ lookup('file', 'files/id_rsa.pub') }}"
        create: true
        backup: true
        state: present
    
    - name: Debug
      debug:
        msg: "Testing the prompt values: user={{ op_account }}, passwd={{ op_password }}, uid={{ op_uid }}, gid={{ op_gid }}"
    
...
